"""内置种子知识库。

内容与《AI电话调解机器人_资料准备字段模板.xlsx》逐行对应（V1.0, 2026-06-10），
并以 remark="系统补充" 标注少量为打通完整对话链路而新增的路由/话术/标签。
该模块同时服务于：① scripts/seed_db.py 灌库 ② offline_mode 直接构建内存快照 ③ 单元测试。
"""

# ---------------- 03_SOP节点表（N001~N025） ----------------
# auto_chain=True：该节点为"陈述型"，话术说完后在同一回合自动衔接 default_next 的主问句
NODES = [
    dict(node_id="N001", node_name="开场问候", stage="开场", node_goal="说明来电机构并开始沟通",
         entry_template_id="TPL_OPEN_001", required_slots=[], default_next="N002", fallback_node="N024",
         max_retry=1, allow_template=True, allow_llm=False, auto_chain=True,
         forbidden_actions="不得直接披露案件金额/平台", remark="开场应短"),
    dict(node_id="N002", node_name="身份确认", stage="身份核验", node_goal="确认是否为当事人本人",
         entry_template_id="TPL_ASK_SELF_001", required_slots=["identity_confirmed"], default_next="N006",
         fallback_node="N003", max_retry=2, allow_template=True, allow_llm=False, auto_chain=False,
         forbidden_actions="不得披露平台、金额、债务详情", remark="隐私保护核心节点"),
    dict(node_id="N003", node_name="身份解释", stage="身份核验", node_goal="用户询问来电身份时进行说明",
         entry_template_id="TPL_IDENTITY_001", required_slots=[], default_next="N002", fallback_node="N004",
         max_retry=2, allow_template=True, allow_llm=True, auto_chain=True,
         forbidden_actions="不得披露案件详情"),
    dict(node_id="N004", node_name="官方核验说明", stage="身份核验", node_goal="用户怀疑诈骗时引导官方核验",
         entry_template_id="TPL_AUTH_001", required_slots=[], default_next="N002", fallback_node="N025",
         max_retry=1, allow_template=True, allow_llm=False, auto_chain=False,
         forbidden_actions="不得索要验证码/转账", remark="高风险优先节点"),
    dict(node_id="N005", node_name="非本人处理", stage="身份核验", node_goal="对方非本人时保护隐私并确认是否认识",
         entry_template_id="TPL_NON_SELF_001", required_slots=[], default_next="N024", fallback_node="N024",
         max_retry=1, allow_template=True, allow_llm=False, auto_chain=False,
         forbidden_actions="不得说明具体事项", remark="不向第三方披露"),
    dict(node_id="N006", node_name="调解事项告知", stage="事项告知", node_goal="确认本人后说明调解事项",
         entry_template_id="TPL_CASE_NOTICE_001", required_slots=["platform_name"], default_next="N007",
         fallback_node="N012", max_retry=1, allow_template=True, allow_llm=True, auto_chain=True,
         forbidden_actions="不得威胁或定性违法", remark="只做有限告知"),
    dict(node_id="N007", node_name="通知确认", stage="事项告知", node_goal="确认是否收到短信/通知",
         entry_template_id="TPL_NOTICE_ASK_001", required_slots=[], default_next="N009", fallback_node="N008",
         max_retry=1, allow_template=True, allow_llm=False, auto_chain=False,
         forbidden_actions="不得强迫点击链接"),
    dict(node_id="N008", node_name="通知补充说明", stage="事项告知", node_goal="没收到通知时补充说明",
         entry_template_id="TPL_NOTICE_001", required_slots=[], default_next="N009", fallback_node="N009",
         max_retry=1, allow_template=True, allow_llm=True, auto_chain=True,
         forbidden_actions="不得要求立即处理"),
    dict(node_id="N009", node_name="调解意愿确认", stage="意愿确认", node_goal="询问是否愿意参与调解",
         entry_template_id="TPL_WILL_001", required_slots=["mediation_willingness"], default_next="N010",
         fallback_node="N012", max_retry=2, allow_template=True, allow_llm=True, auto_chain=False,
         forbidden_actions="不得强迫调解"),
    dict(node_id="N010", node_name="愿意调解", stage="意愿确认", node_goal="进入方案或争议沟通",
         entry_template_id="TPL_ACCEPT_001", required_slots=[], default_next="N017", fallback_node="N017",
         max_retry=1, allow_template=True, allow_llm=True, auto_chain=True,
         forbidden_actions="不得承诺结果"),
    dict(node_id="N011", node_name="拒调记录", stage="意愿确认", node_goal="尊重拒绝并记录意见",
         entry_template_id="TPL_REFUSE_001", required_slots=[], default_next="N024", fallback_node="N024",
         max_retry=1, allow_template=True, allow_llm=False, auto_chain=True,
         forbidden_actions="不得施压/恐吓"),
    dict(node_id="N012", node_name="犹豫观望", stage="意愿确认", node_goal="用户不明确时解释调解作用",
         entry_template_id="TPL_HESITATE_001", required_slots=[], default_next="N009", fallback_node="N022",
         max_retry=2, allow_template=True, allow_llm=True, auto_chain=True,
         forbidden_actions="不得强迫表态"),
    dict(node_id="N013", node_name="否认欠款处理", stage="争议处理", node_goal="用户否认欠款时记录异议",
         entry_template_id="TPL_DENY_001", required_slots=[], default_next="N009", fallback_node="N025",
         max_retry=1, allow_template=True, allow_llm=True, auto_chain=True,
         forbidden_actions="不得争辩或直接定性"),
    dict(node_id="N014", node_name="已还款处理", stage="争议处理", node_goal="用户称已还款时引导提交凭证",
         entry_template_id="TPL_PAID_001", required_slots=[], default_next="N023", fallback_node="N025",
         max_retry=1, allow_template=True, allow_llm=False, auto_chain=True,
         forbidden_actions="不得否定用户"),
    dict(node_id="N015", node_name="金额异议处理", stage="争议处理", node_goal="用户对金额有异议时记录核对",
         entry_template_id="TPL_AMOUNT_001", required_slots=[], default_next="N017", fallback_node="N025",
         max_retry=1, allow_template=True, allow_llm=True, auto_chain=True,
         forbidden_actions="不得强行确认金额"),
    dict(node_id="N016", node_name="平台质疑处理", stage="争议处理", node_goal="用户质疑平台/来源",
         entry_template_id="TPL_PLATFORM_001", required_slots=[], default_next="N009", fallback_node="N025",
         max_retry=1, allow_template=True, allow_llm=True, auto_chain=True,
         forbidden_actions="不得替平台做承诺"),
    dict(node_id="N017", node_name="方案沟通", stage="方案协商", node_goal="引导用户提出处理方案",
         entry_template_id="TPL_PLAN_ASK_001", required_slots=["repayment_amount", "repayment_date"],
         default_next="N021", fallback_node="N018", max_retry=2, allow_template=True, allow_llm=True,
         auto_chain=False, forbidden_actions="不得施压立即还款", remark="核心协商节点"),
    dict(node_id="N018", node_name="无力还款处理", stage="方案协商", node_goal="用户表示没钱时共情并探询",
         entry_template_id="TPL_NO_MONEY_001", required_slots=[], default_next="N017", fallback_node="N022",
         max_retry=2, allow_template=True, allow_llm=True, auto_chain=False,
         forbidden_actions="不得威胁/羞辱"),
    dict(node_id="N019", node_name="分期方案收集", stage="方案协商", node_goal="收集分期期数和金额",
         entry_template_id="TPL_INSTALLMENT_001", required_slots=["installment_count", "installment_amount"],
         default_next="N021", fallback_node="N017", max_retry=2, allow_template=True, allow_llm=True,
         auto_chain=False, forbidden_actions="不得承诺通过"),
    dict(node_id="N020", node_name="减免诉求记录", stage="方案协商", node_goal="记录减免诉求但不承诺",
         entry_template_id="TPL_REDUCTION_001", required_slots=[], default_next="N017", fallback_node="N023",
         max_retry=1, allow_template=True, allow_llm=False, auto_chain=True,
         forbidden_actions="不得承诺减免结果"),
    dict(node_id="N021", node_name="方案确认", stage="方案协商", node_goal="复述并确认用户方案",
         entry_template_id="TPL_PLAN_CONFIRM_001", required_slots=["repayment_amount", "repayment_date"],
         default_next="N023", fallback_node="N017", max_retry=1, allow_template=True, allow_llm=True,
         auto_chain=False, forbidden_actions="不得扩大承诺"),
    dict(node_id="N022", node_name="预约回访", stage="预约结束", node_goal="约定后续沟通时间",
         entry_template_id="TPL_CALLBACK_001", required_slots=["callback_time"], default_next="N024",
         fallback_node="N024", max_retry=1, allow_template=True, allow_llm=True, auto_chain=False,
         forbidden_actions="不得频繁骚扰"),
    dict(node_id="N023", node_name="通话总结", stage="预约结束", node_goal="总结本次沟通结果",
         entry_template_id="TPL_SUMMARY_001", required_slots=[], default_next="N024", fallback_node="N024",
         max_retry=1, allow_template=True, allow_llm=True, auto_chain=True,
         forbidden_actions="不得加入未确认承诺"),
    dict(node_id="N024", node_name="正常结束", stage="预约结束", node_goal="礼貌结束电话",
         entry_template_id="TPL_END_001", required_slots=[], default_next="END", fallback_node="END",
         max_retry=0, allow_template=True, allow_llm=False, auto_chain=False,
         forbidden_actions="不得继续追问"),
    dict(node_id="N025", node_name="转人工", stage="异常兜底", node_goal="高风险或复杂问题转人工",
         entry_template_id="TPL_TRANSFER_001", required_slots=[], default_next="END", fallback_node="END",
         max_retry=0, allow_template=True, allow_llm=False, auto_chain=False,
         forbidden_actions="不得继续争辩"),
]

TERMINAL_END, TERMINAL_TRANSFER = "N024", "N025"

# ---------------- 04_意图抗性标签表（Excel原表 + 系统补充） ----------------
LABELS = [
    dict(label_id="CONFIRM_SELF", label_type="意图", label_name="确认本人", category="身份类",
         keywords=["我是", "我就是", "是我", "本人", "你说吧", "说吧"], risk_level="低",
         suggest_node="N006", global_priority=False, confidence_min=0.75, objection_label=None,
         remark="更新identity_confirmed=true"),
    dict(label_id="NOT_SELF", label_type="意图", label_name="非本人", category="身份类",
         keywords=["不是本人", "我不是本人", "我不是当事人", "我不是他", "我不是她",
                   "打错", "打错了", "您打错", "你打错", "打错电话", "电话打错",
                   "不是我", "他不在", "她不在", "他没在", "她没在", "不在家",
                   "你找错", "您找错", "找错人", "找错号", "号码错了",
                   "搞错了", "弄错了", "不认识你说的", "不是这个人"],
         risk_level="中", suggest_node="N005", global_priority=True, confidence_min=0.75,
         objection_label="THIRD_PARTY", remark="保护隐私"),
    dict(label_id="QUESTION_IDENTITY", label_type="意图", label_name="询问来电身份", category="身份类",
         keywords=["你是谁", "你们是谁", "哪位", "你哪位", "什么事", "干什么", "哪里打来", "什么机构"],
         risk_level="中", suggest_node="N003", global_priority=False, confidence_min=0.7,
         objection_label="DOUBT_IDENTITY"),
    dict(label_id="FRAUD_SUSPICION", label_type="意图", label_name="怀疑诈骗", category="风险类",
         keywords=["骗子", "诈骗", "骗人", "真的假的", "真假", "怎么证明", "凭什么信", "不会是骗"],
         risk_level="高", suggest_node="N004", global_priority=True, confidence_min=0.7,
         objection_label="DOUBT_IDENTITY", remark="全局优先"),
    dict(label_id="NOTICE_NOT_RECEIVED", label_type="意图", label_name="未收到通知", category="通知类",
         keywords=["没收到", "没有收到", "没看到短信", "没接到", "不知道这个事", "什么短信", "什么通知"],
         risk_level="中", suggest_node="N008", global_priority=False, confidence_min=0.7,
         objection_label="NOTICE_OBJECTION"),
    dict(label_id="ACCEPT_MEDIATION", label_type="意图", label_name="愿意调解", category="意愿类",
         keywords=["愿意", "可以调解", "可以沟通", "可以商量", "协商", "怎么处理", "怎么解决", "想处理"],
         risk_level="低", suggest_node="N010", global_priority=False, confidence_min=0.7,
         objection_label=None),
    dict(label_id="REFUSE_MEDIATION", label_type="意图", label_name="拒绝调解", category="意愿类",
         keywords=["不调解", "别打了", "不要再打", "别再打", "不处理", "不沟通", "别烦", "不需要调解"],
         risk_level="中", suggest_node="N011", global_priority=True, confidence_min=0.75,
         objection_label="REFUSE", remark="尊重拒调"),
    dict(label_id="DENY_DEBT", label_type="抗性", label_name="否认欠款", category="争议类",
         keywords=["没借", "没有借", "不是我的钱", "没有这回事", "没欠", "我不欠", "没贷过"],
         risk_level="高", suggest_node="N013", global_priority=False, confidence_min=0.75,
         objection_label="DENY_DEBT", remark="不争辩"),
    dict(label_id="ALREADY_PAID", label_type="抗性", label_name="已还款", category="争议类",
         keywords=["已经还", "早就还", "还清", "还完了", "结清", "之前还过", "前阵子还了",
                   "我之前给过", "前段时间处理了"], risk_level="中",
         suggest_node="N014", global_priority=False, confidence_min=0.75,
         objection_label="ALREADY_PAID", remark="引导凭证"),
    dict(label_id="AMOUNT_DISPUTE", label_type="抗性", label_name="金额异议", category="争议类",
         keywords=["金额不对", "数目不对", "利息太高", "利息高", "算错", "怎么这么多", "哪来这么多"],
         risk_level="中", suggest_node="N015", global_priority=False, confidence_min=0.7,
         objection_label="AMOUNT_DISPUTE"),
    dict(label_id="PLATFORM_QUESTION", label_type="抗性", label_name="平台质疑", category="争议类",
         keywords=["什么平台", "哪个平台", "没用过", "没听过这个平台"], risk_level="中",
         suggest_node="N016", global_priority=False, confidence_min=0.7,
         objection_label="PLATFORM_QUESTION"),
    dict(label_id="NO_MONEY", label_type="抗性", label_name="暂无还款能力", category="能力类",
         keywords=["没钱", "没有钱", "失业", "失业了", "没工作", "工资没发", "工资还没发",
                   "还不上", "还不起", "拿不出", "周转不开", "确实困难", "实在没办法",
                   "孩子上学", "孩子学费", "家里人生病", "家人住院", "看病", "看病去了",
                   "刚交了房租", "还了房贷", "刚发工资就", "暂时拿不出", "家里有事"],
         risk_level="中", suggest_node="N018", global_priority=False, confidence_min=0.7,
         objection_label="NO_PAYMENT_ABILITY", remark="共情探询"),
    dict(label_id="REQUEST_INSTALLMENT", label_type="意图", label_name="请求分期", category="方案类",
         keywords=["分期", "分几期", "每月还", "一个月还", "慢慢还", "分次还"], risk_level="低",
         suggest_node="N019", global_priority=False, confidence_min=0.7,
         objection_label="INSTALLMENT_REQUEST", remark="收集期数金额"),
    dict(label_id="REQUEST_REDUCTION", label_type="意图", label_name="请求减免", category="方案类",
         keywords=["减免", "少还点", "免掉", "利息能不能免", "只还本金", "减一点", "打个折"],
         risk_level="中", suggest_node="N020", global_priority=False, confidence_min=0.7,
         objection_label="REDUCTION_REQUEST", remark="不得承诺"),
    dict(label_id="PROVIDE_PLAN", label_type="意图", label_name="提供方案", category="方案类",
         keywords=[], risk_level="低", suggest_node="N021", global_priority=False, confidence_min=0.65,
         objection_label=None, remark="由槽位抽取推断"),
    dict(label_id="REQUEST_CALLBACK", label_type="意图", label_name="要求回访", category="预约类",
         keywords=["不方便", "再打", "等会打", "晚点联系", "晚点打", "在开会", "在忙", "改天"],
         risk_level="低", suggest_node="N022", global_priority=False, confidence_min=0.7,
         objection_label=None, remark="记录时间"),
    dict(label_id="REQUEST_HUMAN", label_type="意图", label_name="要求人工", category="风险类",
         keywords=["人工", "真人", "转人工", "你们领导", "负责人", "找你们经理"], risk_level="高",
         suggest_node="N025", global_priority=True, confidence_min=0.7, objection_label=None),
    dict(label_id="COMPLAINT_THREAT", label_type="风险", label_name="投诉威胁", category="风险类",
         keywords=["投诉", "举报", "报警", "曝光", "我录音了", "骚扰", "起诉你们", "12345"],
         risk_level="高", suggest_node="N025", global_priority=True, confidence_min=0.65,
         objection_label="COMPLAINT", remark="转人工或降温"),
    dict(label_id="ABUSIVE_LANGUAGE", label_type="风险", label_name="辱骂情绪", category="风险类",
         keywords=["滚", "妈的", "他妈", "你妈", "神经病", "有病", "傻"], risk_level="高",
         suggest_node="N025", global_priority=True, confidence_min=0.65,
         objection_label="COMPLAINT", remark="降温结束"),
    dict(label_id="UNKNOWN", label_type="意图", label_name="无法识别", category="兜底类",
         keywords=[], risk_level="中", suggest_node=None, global_priority=False, confidence_min=0.0,
         objection_label=None, remark="进入fallback"),
    # ---- 系统补充标签 ----
    dict(label_id="NOTICE_RECEIVED", label_type="意图", label_name="已收到通知", category="通知类",
         keywords=["收到了", "看到了", "收到短信", "收到过", "有收到", "收到", "知道这个事", "了解了"], risk_level="低",
         suggest_node="N009", global_priority=False, confidence_min=0.7, objection_label=None,
         remark="系统补充"),
    dict(label_id="HESITATE", label_type="意图", label_name="犹豫观望", category="意愿类",
         keywords=["再说吧", "考虑", "考虑一下", "考虑下", "看看吧", "想想", "想想吧",
                   "再联系", "到时候再说", "和家里商量", "跟家里人说", "我得问问家里",
                   "我得想想"], risk_level="低",
         suggest_node="N012", global_priority=False, confidence_min=0.65, objection_label=None,
         remark="系统补充"),
    dict(label_id="KNOWS_PERSON", label_type="意图", label_name="认识当事人", category="身份类",
         keywords=["认识", "是我家人", "我老公", "我老婆", "我儿子", "我朋友"], risk_level="低",
         suggest_node="N024", global_priority=False, confidence_min=0.7, objection_label=None,
         remark="系统补充：仅N005语境"),
    dict(label_id="NOT_KNOW", label_type="意图", label_name="不认识当事人", category="身份类",
         keywords=["不认识"], risk_level="低", suggest_node="N024", global_priority=False,
         confidence_min=0.7, objection_label=None, remark="系统补充：仅N005语境"),
    dict(label_id="PLAN_AGREE", label_type="意图", label_name="确认方案无误", category="方案类",
         keywords=["没问题", "没错", "是的对"], risk_level="低", suggest_node="N023",
         global_priority=False, confidence_min=0.7, objection_label=None, remark="系统补充：仅N021语境"),
    dict(label_id="PLAN_ADJUST", label_type="意图", label_name="方案需调整", category="方案类",
         keywords=["不对", "不是这样", "改一下", "换个时间"], risk_level="低", suggest_node="N017",
         global_priority=False, confidence_min=0.7, objection_label=None, remark="系统补充：仅N021语境"),
    dict(label_id="AFFIRM", label_type="系统", label_name="通用肯定", category="兜底类",
         keywords=["嗯", "对", "是", "好", "行", "可以", "好的", "是的", "对的", "没问题", "ok", "OK", "中"],
         risk_level="低", suggest_node=None, global_priority=False, confidence_min=0.6,
         objection_label=None, remark="系统补充：按节点极性映射"),
    dict(label_id="DENY", label_type="系统", label_name="通用否定", category="兜底类",
         keywords=["不是", "没有", "不", "不行", "不用", "没", "不好", "不可以"],
         risk_level="低", suggest_node=None, global_priority=False, confidence_min=0.6,
         objection_label=None, remark="系统补充：按节点极性映射"),
]

# 通用肯定/否定 → 按当前监听节点映射为业务标签
NODE_POLAR_MAP = {
    "N002": {"AFFIRM": "CONFIRM_SELF", "DENY": "NOT_SELF"},
    "N003": {"AFFIRM": "CONFIRM_SELF", "DENY": "NOT_SELF"},
    "N004": {"AFFIRM": "CONFIRM_SELF", "DENY": "NOT_SELF"},
    "N005": {"AFFIRM": "KNOWS_PERSON", "DENY": "NOT_KNOW"},
    "N007": {"AFFIRM": "NOTICE_RECEIVED", "DENY": "NOTICE_NOT_RECEIVED"},
    "N009": {"AFFIRM": "ACCEPT_MEDIATION", "DENY": "REFUSE_MEDIATION"},
    "N012": {"AFFIRM": "ACCEPT_MEDIATION", "DENY": "REFUSE_MEDIATION"},
    "N021": {"AFFIRM": "PLAN_AGREE", "DENY": "PLAN_ADJUST"},
}

# 标签命中后自动写入的槽位（与02表"业务结果"字段一致）
# CONFIRM_SELF 必须同时把 not_self 拉回 False：否则之前误判的 not_self=True 会一直留存，
# 让 CR005 在用户已确认身份后还把含金额的复述吞成"为保护隐私我不便说明具体内容"。
LABEL_SLOT_EFFECTS = {
    "CONFIRM_SELF": {"identity_confirmed": True, "not_self": False},
    "NOT_SELF": {"not_self": True},
    "ACCEPT_MEDIATION": {"willingness": True, "mediation_willingness": "愿意"},
    "REFUSE_MEDIATION": {"willingness": False, "mediation_willingness": "拒绝"},
    "HESITATE": {"mediation_willingness": "犹豫"},
    "DENY_DEBT": {"debt_disputed": True},
    "ALREADY_PAID": {"paid_claimed": True},
    "AMOUNT_DISPUTE": {"amount_disputed": True},
    "PLATFORM_QUESTION": {"platform_disputed": True},
    "REQUEST_REDUCTION": {"reduction_request": True},
    "NO_MONEY": {"no_money": True},
}

# ---------------- 05_决策路由表（Excel R001~R020 + 系统补充 R1xx） ----------------
def _r(route_id, cur, intent, cond, nxt, action, strategy=None, template=None,
       comps=None, prio=50, g=False, conf=0.0, risk=None, sets=None, remark=""):
    return dict(route_id=route_id, current_node=cur, intent_label=intent,
                slot_condition=cond or {}, risk_level=risk, confidence_min=conf,
                next_node=nxt, action_type=action, strategy_id=strategy, template_id=template,
                prompt_component_ids=comps or [], set_slots=sets or {}, priority=prio,
                is_global=g, enabled=True, remark=remark)


_LLM_COMPS = ["ROLE", "HISTORY", "NODE", "USER_TEXT", "KNOWN", "STRATEGY", "SCRIPT",
              "COMPLIANCE", "NO_REPEAT", "OUTPUT"]

ROUTES = [
    # ---- Excel 原表 R001~R020 ----
    _r("R001", "ANY", "REQUEST_HUMAN", {}, "N025", "TRANSFER_HUMAN", "STR_TRANSFER",
       "TPL_TRANSFER_001", prio=100, g=True, conf=0.7, risk="高", remark="用户要求人工优先"),
    _r("R002", "ANY", "FRAUD_SUSPICION", {}, "N004", "DIRECT_TEMPLATE", "STR_AUTH_VERIFY",
       "TPL_AUTH_001", prio=98, g=True, conf=0.7, risk="高", remark="怀疑诈骗优先"),
    _r("R003", "ANY", "COMPLAINT_THREAT", {}, "N025", "DIRECT_TEMPLATE", "STR_COMPLAINT",
       "TPL_TRANSFER_001", prio=97, g=True, conf=0.65, risk="高", remark="投诉威胁"),
    _r("R004", "ANY", "ABUSIVE_LANGUAGE", {}, "N025", "DIRECT_TEMPLATE", "STR_COOLDOWN",
       "TPL_COOLDOWN_001", prio=96, g=True, conf=0.65, risk="高", remark="辱骂降温"),
    _r("R005", "N002", "CONFIRM_SELF", {"identity_confirmed": False}, "N006", "DIRECT_TEMPLATE",
       "STR_CASE_NOTICE", "TPL_CASE_NOTICE_001", prio=90, conf=0.75, remark="确认本人后告知事项"),
    _r("R006", "N002", "NOT_SELF", {"identity_confirmed": False}, "N005", "DIRECT_TEMPLATE",
       "STR_NON_SELF", "TPL_NON_SELF_001", prio=90, conf=0.75, remark="非本人"),
    _r("R007", "N002", "QUESTION_IDENTITY", {"identity_confirmed": False}, "N003", "DIRECT_TEMPLATE",
       "STR_PRIVACY_IDENTITY", "TPL_IDENTITY_001", prio=85, conf=0.7, remark="询问身份"),
    _r("R008", "N003", "CONFIRM_SELF", {"identity_confirmed": False}, "N006", "DIRECT_TEMPLATE",
       "STR_CASE_NOTICE", "TPL_CASE_NOTICE_001", prio=90, conf=0.75, remark="解释后确认本人"),
    _r("R009", "N006", "NOTICE_NOT_RECEIVED", {"identity_confirmed": True}, "N008", "DIRECT_TEMPLATE",
       "STR_NOTICE_EXPLAIN", "TPL_NOTICE_001", prio=80, conf=0.7, remark="未收到通知"),
    _r("R010", "N006", "DENY_DEBT", {"identity_confirmed": True}, "N013", "DIRECT_TEMPLATE",
       "STR_DENY_DEBT", "TPL_DENY_001", prio=85, conf=0.75, remark="否认欠款"),
    _r("R011", "N009", "ACCEPT_MEDIATION", {"identity_confirmed": True}, "N010", "DIRECT_TEMPLATE",
       "STR_ACCEPT", "TPL_ACCEPT_001", prio=80, conf=0.7, remark="愿意调解"),
    _r("R012", "N009", "REFUSE_MEDIATION", {"identity_confirmed": True}, "N011", "DIRECT_TEMPLATE",
       "STR_REFUSE", "TPL_REFUSE_001", prio=90, conf=0.75, remark="拒绝调解"),
    _r("R013", "N009", "DENY_DEBT", {"identity_confirmed": True}, "N013", "DIRECT_TEMPLATE",
       "STR_DENY_DEBT", "TPL_DENY_001", prio=85, conf=0.75, remark="意愿阶段否认欠款"),
    _r("R014", "N017", "NO_MONEY", {"willingness": True}, "N018", "LLM_SHORT_REPLY",
       "STR_NO_MONEY", "TPL_NO_MONEY_001", _LLM_COMPS, prio=80, conf=0.7, remark="复杂表达可LLM"),
    _r("R015", "N017", "REQUEST_INSTALLMENT", {"willingness": True}, "N019", "LLM_SHORT_REPLY",
       "STR_INSTALLMENT", "TPL_INSTALLMENT_001", _LLM_COMPS, prio=80, conf=0.7, remark="分期收集"),
    _r("R016", "N017", "REQUEST_REDUCTION", {"willingness": True}, "N020", "DIRECT_TEMPLATE",
       "STR_REDUCTION", "TPL_REDUCTION_001", prio=85, conf=0.7, remark="减免不承诺，模板直出"),
    _r("R017", "N017", "PROVIDE_PLAN", {"willingness": True}, "N021", "LLM_SHORT_REPLY",
       "STR_PLAN_CONFIRM", "TPL_PLAN_CONFIRM_001", ["ROLE", "NODE", "STRATEGY", "SCRIPT", "OUTPUT"],
       prio=80, conf=0.65, remark="需复述方案"),
    _r("R018", "N018", "PROVIDE_PLAN", {"willingness": True}, "N021", "LLM_SHORT_REPLY",
       "STR_PLAN_CONFIRM", "TPL_PLAN_CONFIRM_001", ["ROLE", "NODE", "STRATEGY", "SCRIPT", "OUTPUT"],
       prio=80, conf=0.65, remark="无力后提出方案"),
    _r("R019", "N019", "PROVIDE_PLAN", {"willingness": True}, "N021", "LLM_SHORT_REPLY",
       "STR_PLAN_CONFIRM", "TPL_PLAN_CONFIRM_001", ["ROLE", "NODE", "STRATEGY", "SCRIPT", "OUTPUT"],
       prio=80, conf=0.65, remark="分期方案确认"),
    _r("R020", "ANY", "REQUEST_CALLBACK", {}, "N022", "LLM_SHORT_REPLY", "STR_CALLBACK",
       "TPL_CALLBACK_001", ["ROLE", "NODE", "SCRIPT", "OUTPUT"], prio=70, conf=0.7, remark="预约回访"),

    # ---- 系统补充：打通完整链路（remark=系统补充） ----
    _r("R101", "ANY", "QUESTION_IDENTITY", {"identity_confirmed": False}, "N003", "DIRECT_TEMPLATE",
       "STR_PRIVACY_IDENTITY", "TPL_IDENTITY_001", prio=84, g=True, conf=0.7, remark="系统补充"),
    _r("R102", "ANY", "QUESTION_IDENTITY", {"identity_confirmed": True}, "N006", "DIRECT_TEMPLATE",
       "STR_CASE_NOTICE", "TPL_CASE_NOTICE_001", prio=70, g=True, conf=0.7, remark="系统补充：本人再问事项"),
    _r("R103", "ANY", "NOT_SELF", {"identity_confirmed": False}, "N005", "DIRECT_TEMPLATE",
       "STR_NON_SELF", "TPL_NON_SELF_001", prio=83, g=True, conf=0.75, remark="系统补充"),
    _r("R104", "N004", "CONFIRM_SELF", {}, "N006", "DIRECT_TEMPLATE",
       "STR_CASE_NOTICE", "TPL_CASE_NOTICE_001", prio=90, conf=0.75, remark="系统补充：核验后确认本人"),
    _r("R105", "ANY", "REFUSE_MEDIATION", {}, "N011", "DIRECT_TEMPLATE", "STR_REFUSE",
       "TPL_REFUSE_001", prio=76, g=True, conf=0.7,
       remark="系统补充：任意阶段尊重拒调/停止联系诉求（CR006骚扰规则要求）"),
    _r("R110", "N005", "KNOWS_PERSON", {}, "N024", "DIRECT_TEMPLATE", "STR_NON_SELF",
       "TPL_RELAY_001", prio=90, conf=0.65, sets={"call_result": "非本人"}, remark="系统补充：请其转告"),
    _r("R111", "N005", "NOT_KNOW", {}, "N024", "END_CALL", "STR_NON_SELF",
       "TPL_END_001", prio=88, conf=0.65, sets={"call_result": "非本人"}, remark="系统补充"),
    # 恢复路径：误判为"非本人"后用户澄清"我就是本人" → 回到事项告知，撤回 not_self 标记
    _r("R112", "N005", "CONFIRM_SELF", {}, "N006", "DIRECT_TEMPLATE",
       "STR_CASE_NOTICE", "TPL_CASE_NOTICE_001", prio=95, conf=0.7,
       sets={"identity_confirmed": True, "not_self": False},
       remark="系统补充：N005 误判恢复"),
    _r("R120", "N007", "NOTICE_RECEIVED", {}, "N009", "DIRECT_TEMPLATE", "STR_ACCEPT",
       "TPL_WILL_001", prio=88, conf=0.65, remark="系统补充：收到通知→问意愿"),
    _r("R121", "N007", "NOTICE_NOT_RECEIVED", {}, "N008", "DIRECT_TEMPLATE",
       "STR_NOTICE_EXPLAIN", "TPL_NOTICE_001", prio=90, conf=0.65, remark="系统补充"),
    _r("R122", "N007", "ACCEPT_MEDIATION", {}, "N010", "DIRECT_TEMPLATE", "STR_ACCEPT",
       "TPL_ACCEPT_001", prio=80, conf=0.65, remark="系统补充：直接表达意愿"),
    _r("R123", "N007", "PROVIDE_PLAN", {}, "N021", "DIRECT_TEMPLATE", "STR_PLAN_CONFIRM",
       "TPL_PLAN_CONFIRM_001", prio=82, conf=0.6,
       sets={"willingness": True, "mediation_willingness": "愿意"}, remark="系统补充：提前给方案"),
    _r("R130", "N009", "HESITATE", {}, "N012", "DIRECT_TEMPLATE", "STR_ACCEPT",
       "TPL_HESITATE_001", prio=85, conf=0.6, remark="系统补充：犹豫观望"),
    _r("R131", "N009", "NO_MONEY", {}, "N018", "LLM_SHORT_REPLY", "STR_NO_MONEY",
       "TPL_NO_MONEY_001", _LLM_COMPS, prio=86, conf=0.65,
       sets={"willingness": True, "mediation_willingness": "愿意"}, remark="系统补充：没钱视作进入沟通"),
    _r("R132", "N009", "REQUEST_INSTALLMENT", {}, "N019", "LLM_SHORT_REPLY", "STR_INSTALLMENT",
       "TPL_INSTALLMENT_001", _LLM_COMPS, prio=84, conf=0.65,
       sets={"willingness": True, "mediation_willingness": "愿意"}, remark="系统补充"),
    _r("R133", "N009", "REQUEST_REDUCTION", {}, "N020", "DIRECT_TEMPLATE", "STR_REDUCTION",
       "TPL_REDUCTION_001", prio=84, conf=0.65,
       sets={"willingness": True, "mediation_willingness": "愿意"}, remark="系统补充"),
    _r("R134", "N009", "ALREADY_PAID", {}, "N014", "DIRECT_TEMPLATE", "STR_ALREADY_PAID",
       "TPL_PAID_001", prio=84, conf=0.7, remark="系统补充"),
    _r("R135", "N009", "AMOUNT_DISPUTE", {}, "N015", "DIRECT_TEMPLATE", "STR_DENY_DEBT",
       "TPL_AMOUNT_001", prio=83, conf=0.65,
       sets={"willingness": True, "mediation_willingness": "愿意"}, remark="系统补充"),
    _r("R136", "N009", "PLATFORM_QUESTION", {}, "N016", "DIRECT_TEMPLATE", "STR_DENY_DEBT",
       "TPL_PLATFORM_001", prio=83, conf=0.65, remark="系统补充"),
    _r("R137", "N009", "PROVIDE_PLAN", {}, "N021", "DIRECT_TEMPLATE", "STR_PLAN_CONFIRM",
       "TPL_PLAN_CONFIRM_001", prio=82, conf=0.6,
       sets={"willingness": True, "mediation_willingness": "愿意"}, remark="系统补充：直接给方案"),
    _r("R140", "N017", "REFUSE_MEDIATION", {}, "N011", "DIRECT_TEMPLATE", "STR_REFUSE",
       "TPL_REFUSE_001", prio=85, conf=0.7, remark="系统补充"),
    _r("R141", "N017", "DENY_DEBT", {}, "N013", "DIRECT_TEMPLATE", "STR_DENY_DEBT",
       "TPL_DENY_001", prio=84, conf=0.7, remark="系统补充"),
    _r("R142", "N017", "ALREADY_PAID", {}, "N014", "DIRECT_TEMPLATE", "STR_ALREADY_PAID",
       "TPL_PAID_001", prio=84, conf=0.7, remark="系统补充"),
    _r("R143", "N017", "AMOUNT_DISPUTE", {}, "N015", "DIRECT_TEMPLATE", "STR_DENY_DEBT",
       "TPL_AMOUNT_001", prio=83, conf=0.65, remark="系统补充"),
    _r("R144", "N018", "REQUEST_INSTALLMENT", {}, "N019", "LLM_SHORT_REPLY", "STR_INSTALLMENT",
       "TPL_INSTALLMENT_001", _LLM_COMPS, prio=84, conf=0.65, remark="系统补充"),
    _r("R145", "N018", "REQUEST_REDUCTION", {}, "N020", "DIRECT_TEMPLATE", "STR_REDUCTION",
       "TPL_REDUCTION_001", prio=84, conf=0.65, remark="系统补充"),
    _r("R146", "N018", "NO_MONEY", {}, "N018", "LLM_SHORT_REPLY", "STR_NO_MONEY",
       "TPL_NO_MONEY_001", _LLM_COMPS, prio=60, conf=0.6, remark="系统补充：持续共情"),
    _r("R147", "N018", "REFUSE_MEDIATION", {}, "N011", "DIRECT_TEMPLATE", "STR_REFUSE",
       "TPL_REFUSE_001", prio=85, conf=0.7, remark="系统补充"),
    _r("R148", "N019", "NO_MONEY", {}, "N018", "LLM_SHORT_REPLY", "STR_NO_MONEY",
       "TPL_NO_MONEY_001", _LLM_COMPS, prio=80, conf=0.65, remark="系统补充"),
    _r("R149", "N019", "REFUSE_MEDIATION", {}, "N011", "DIRECT_TEMPLATE", "STR_REFUSE",
       "TPL_REFUSE_001", prio=85, conf=0.7, remark="系统补充"),
    _r("R150", "N021", "PLAN_AGREE", {}, "N023", "DIRECT_TEMPLATE", "STR_PLAN_CONFIRM",
       "TPL_SUMMARY_001", prio=90, conf=0.6, sets={"call_result": "达成方案"},
       remark="系统补充：方案达成"),
    _r("R151", "N021", "PLAN_ADJUST", {}, "N017", "DIRECT_TEMPLATE", "STR_PLAN_CONFIRM",
       "TPL_PLAN_ADJUST_001", prio=88, conf=0.6, remark="系统补充：调整方案"),
    _r("R152", "N021", "PROVIDE_PLAN", {}, "N021", "DIRECT_TEMPLATE", "STR_PLAN_CONFIRM",
       "TPL_PLAN_CONFIRM_001", prio=85, conf=0.6, remark="系统补充：改口新方案再确认"),
    _r("R153", "N021", "REQUEST_REDUCTION", {}, "N020", "DIRECT_TEMPLATE", "STR_REDUCTION",
       "TPL_REDUCTION_001", prio=84, conf=0.65, remark="系统补充"),
    _r("R160", "N022", "PROVIDE_PLAN", {"callback_time": "__present__"}, "N024", "DIRECT_TEMPLATE",
       "STR_CALLBACK", "TPL_CALLBACK_OK_001", prio=90, conf=0.6,
       sets={"call_result": "预约回访"}, remark="系统补充：回访时间确认并结束"),
    _r("R161", "N022", "REQUEST_CALLBACK", {"callback_time": "__present__"}, "N024", "DIRECT_TEMPLATE",
       "STR_CALLBACK", "TPL_CALLBACK_OK_001", prio=89, conf=0.6,
       sets={"call_result": "预约回访"}, remark="系统补充"),
    _r("R170", "N024", "ANY", {}, "N024", "END_CALL", None, "TPL_END_001", prio=10,
       remark="系统补充：终态兜底"),
]

# ---------------- 06_调解策略库（Excel 原表） ----------------
def _s(sid, name, nodes, intents, goal, instr, allowed, forbidden, need_llm, risk, fb):
    return dict(strategy_id=sid, strategy_name=name, nodes=nodes, intents=intents, goal=goal,
                instruction=instr, allowed_actions=allowed, forbidden_actions=forbidden,
                need_llm=need_llm, risk_level=risk, fallback_template_id=fb)


STRATEGIES = [
    _s("STR_PRIVACY_IDENTITY", "身份隐私保护", "N002,N003", "QUESTION_IDENTITY", "确认本人并保护隐私",
       "未确认本人前只能说明调解机构和民事调解事项，不披露平台、金额、欠款、逾期、案号。",
       "说明身份、询问是否本人", "披露债务详情、向第三方说明案情", "否", "高", "TPL_IDENTITY_001"),
    _s("STR_AUTH_VERIFY", "官方核验引导", "N004", "FRAUD_SUSPICION", "降低诈骗疑虑",
       "认可用户谨慎，提供官方核验渠道，不索要验证码或转账。",
       "引导核验、保持中性", "要求用户立即操作、索要验证码", "否", "高", "TPL_AUTH_001"),
    _s("STR_NON_SELF", "非本人隐私保护", "N005", "NOT_SELF", "保护当事人隐私",
       "对方非本人时不得披露具体事项，可询问是否认识或是否方便转达。",
       "询问是否认识、礼貌结束", "透露平台、金额、欠款", "否", "高", "TPL_NON_SELF_001"),
    _s("STR_CASE_NOTICE", "调解事项告知", "N006", "CONFIRM_SELF", "中性说明事项",
       "确认本人后，简短说明调解事项来源和沟通目的。",
       "说明平台/委托方、询问是否了解", "威胁、定性违法", "可", "中", "TPL_CASE_NOTICE_001"),
    _s("STR_NOTICE_EXPLAIN", "通知补充说明", "N008", "NOTICE_NOT_RECEIVED", "补充说明通知信息",
       "用户没收到通知时，说明可核验或重新发送，不强迫点击链接。",
       "说明通知渠道、继续询问意愿", "强迫点击、催促处理", "可", "中", "TPL_NOTICE_001"),
    _s("STR_ACCEPT", "承接愿意调解", "N010", "ACCEPT_MEDIATION", "进入方案沟通",
       "用户愿意沟通时，先简短确认听到其态度，再用开放式提问把决定权交给用户，"
       "让用户自己说出时间/金额的初步想法；不替用户决定、不抛具体方案。",
       "承接态度、开放提问", "替用户决定、承诺结果", "可", "低", "TPL_ACCEPT_001"),
    _s("STR_REFUSE", "尊重拒调", "N011", "REFUSE_MEDIATION", "合规结束或记录",
       "调解自愿，用户拒绝时如实记录，不施压。", "记录拒绝、礼貌结束", "恐吓、持续纠缠", "否", "中", "TPL_REFUSE_001"),
    _s("STR_DENY_DEBT", "否认欠款处理", "N013", "DENY_DEBT", "记录争议",
       "用户对欠款有异议。先承接其质疑（如'您的疑问我会如实记录'），"
       "再说明可通过官方账单/合同核对，引导核实而非辩论，作为中立第三方不预设事实。",
       "记录异议、引导核对", "争辩、定性欠款事实", "可", "高", "TPL_DENY_001"),
    _s("STR_ALREADY_PAID", "已还款凭证", "N014", "ALREADY_PAID", "记录并引导凭证",
       "用户称已还款时，引导提交凭证，后续核实。", "记录、引导凭证", "直接否定用户", "否", "中", "TPL_PAID_001"),
    _s("STR_NO_MONEY", "无力还款共情", "N018", "NO_MONEY", "降低抵触并探询可承受方案",
       "用户表达资金困难。先用一句话承接其难处（如理解、不容易、知道您也想处理），"
       "再用开放式提问探询能承受的时间或金额，让用户自己提出方案。"
       "调解的目标是找到双方都能接受的安排，绝不施压、不强求一次还清、不评判。",
       "共情、探询方案", "威胁、羞辱、要求立即还款", "是", "中", "TPL_NO_MONEY_001"),
    _s("STR_INSTALLMENT", "分期方案收集", "N019", "REQUEST_INSTALLMENT", "收集分期要素",
       "询问分几期、每期金额、首期时间，不承诺通过。",
       "收集期数金额时间", "承诺一定通过", "是", "低", "TPL_INSTALLMENT_001"),
    _s("STR_REDUCTION", "减免诉求记录", "N020", "REQUEST_REDUCTION", "记录诉求不承诺",
       "可以记录减免诉求，但不得承诺减免结果。", "记录诉求、说明需核实", "承诺减免、诱导承诺", "否", "中", "TPL_REDUCTION_001"),
    _s("STR_PLAN_CONFIRM", "方案复述确认", "N021", "PROVIDE_PLAN", "确认方案准确性",
       "复述用户提出的金额、时间、期数，确认是否准确。", "复述确认、记录", "增加用户未说内容", "是", "低", "TPL_PLAN_CONFIRM_001"),
    _s("STR_CALLBACK", "预约回访", "N022", "REQUEST_CALLBACK", "确定回访时间",
       "用户不方便时不强求当下沟通，温和约一个用户方便的具体时间，"
       "强调按用户方便来安排，绝不频繁打扰。",
       "询问用户方便时间、记录预约", "强行追问、频繁致电", "是", "低", "TPL_CALLBACK_001"),
    _s("STR_TRANSFER", "转人工", "N025", "REQUEST_HUMAN/高风险", "风险兜底",
       "用户要求人工或风险高时，转人工或记录人工回访。", "转人工、记录", "继续争辩", "否", "高", "TPL_TRANSFER_001"),
    _s("STR_COMPLAINT", "投诉降温", "N025", "COMPLAINT_THREAT", "降低冲突",
       "用户投诉或威胁时，先安抚记录，必要时转人工。", "安抚、记录、转人工", "对抗、刺激用户", "否", "高", "TPL_TRANSFER_001"),
    _s("STR_COOLDOWN", "情绪降温", "N025", "ABUSIVE_LANGUAGE", "降低冲突",
       "用户辱骂或情绪激烈时，降低表达强度，必要时结束。", "安抚、结束、转人工", "对骂、刺激用户", "否", "高", "TPL_COOLDOWN_001"),
]

# ---------------- 07_话术模板库（Excel 原表 + 系统补充） ----------------
def _t(tid, node, sid, intent, text, varlist=None, direct=True, rewrite=False,
       level="高", score=95, remark="", variants=None):
    return dict(template_id=tid, node_id=node, strategy_id=sid, intent_label=intent,
                template_text=text, variables=varlist or [], can_direct=direct,
                need_rewrite=rewrite, compliance_level=level, quality_score=score,
                enabled=True, remark=remark, variants=variants or [])


TEMPLATES = [
    # Excel 原表
    _t("TPL_OPEN_001", "N001", "STR_PRIVACY_IDENTITY", "开场",
       "您好，我这边是{mediation_org}工作人员，想和您确认一项民事调解事项。", ["mediation_org"], remark="开场"),
    _t("TPL_IDENTITY_001", "N003", "STR_PRIVACY_IDENTITY", "QUESTION_IDENTITY",
       "我这边是{mediation_org}工作人员，涉及一项民事调解事项，需要先确认本人后再说明。",
       ["mediation_org"], score=98, remark="未确认本人专用"),
    _t("TPL_AUTH_001", "N004", "STR_AUTH_VERIFY", "FRAUD_SUSPICION",
       "您的谨慎是对的，可以先通过官方渠道核验，我们不会索要验证码或要求转账。",
       ["official_verify_channel"], score=98, remark="怀疑诈骗"),
    _t("TPL_NON_SELF_001", "N005", "STR_NON_SELF", "NOT_SELF",
       "好的，为保护隐私我不便说明具体内容，请问您认识{name}吗？", ["name"], score=96, remark="非本人"),
    _t("TPL_CASE_NOTICE_001", "N006", "STR_CASE_NOTICE", "CONFIRM_SELF",
       "好的，这边是受{creditor_name}委托，关于您在{platform_name}的一项民事调解事项。",
       ["platform_name", "creditor_name"], level="中", score=90, remark="确认本人后使用"),
    _t("TPL_NOTICE_001", "N008", "STR_NOTICE_EXPLAIN", "NOTICE_NOT_RECEIVED",
       "没关系，我这边可以先简单说明，您也可以通过官方渠道核验。", ["official_verify_channel"],
       rewrite=False, score=92),
    _t("TPL_ACCEPT_001", "N010", "STR_ACCEPT", "ACCEPT_MEDIATION",
       "好的，那我先了解一下您这边目前希望怎么处理。", score=92, remark="进入方案"),
    _t("TPL_REFUSE_001", "N011", "STR_REFUSE", "REFUSE_MEDIATION",
       "可以的，调解是自愿的，我会如实记录您的意见。", score=98, remark="拒调"),
    _t("TPL_DENY_001", "N013", "STR_DENY_DEBT", "DENY_DEBT",
       "您的异议我会如实记录，您也可以先核对平台账单或相关材料。", score=95, remark="否认欠款"),
    _t("TPL_PAID_001", "N014", "STR_ALREADY_PAID", "ALREADY_PAID",
       "好的，您可以保留或提交相关还款凭证，后续会进一步核实。", score=95, remark="已还款"),
    _t("TPL_NO_MONEY_001", "N018", "STR_NO_MONEY", "NO_MONEY",
       "您说的难处我也能理解，调解就是想帮您找到一个您能承担的方案，"
       "您看时间或金额上，您这边大概能怎么安排？", direct=True, rewrite=True,
       score=94, remark="建议LLM改写更自然，强调中立第三方与开放式询问",
       variants=["谁都有难处，您先说说目前能周转的时间或金额，咱们一起想个您能接受的方式。",
                 "您的情况我也理解，您看时间上或金额上，您这边大致能承担怎样的安排？",
                 "确实不容易，您能告诉我大致什么时间、多少金额您能接受吗？我帮您反馈过去。"]),
    _t("TPL_INSTALLMENT_001", "N019", "STR_INSTALLMENT", "REQUEST_INSTALLMENT",
       "可以，您可以说一下希望分几期、每期大概能承担多少。", direct=True, rewrite=True, score=94, remark="分期"),
    _t("TPL_REDUCTION_001", "N020", "STR_REDUCTION", "REQUEST_REDUCTION",
       "您的减免诉求我可以记录，具体结果需要后续核实确认。", score=98, remark="减免不承诺"),
    _t("TPL_PLAN_CONFIRM_001", "N021", "STR_PLAN_CONFIRM", "PROVIDE_PLAN",
       "我跟您确认一下，您是计划在{repayment_date}处理{repayment_amount}元，对吗？",
       ["repayment_date", "repayment_amount"], direct=True, rewrite=True, score=92, remark="需变量完整"),
    _t("TPL_CALLBACK_001", "N022", "STR_CALLBACK", "REQUEST_CALLBACK",
       "可以，请问您方便我们什么时间再联系您？", ["callback_time"], direct=True, rewrite=True, score=92, remark="预约"),
    _t("TPL_SUMMARY_001", "N023", "STR_PLAN_CONFIRM", "总结",
       "好的，您刚才的意见我已经如实记录，后续会按流程反馈。", score=90, remark="总结"),
    _t("TPL_END_001", "N024", "STR_REFUSE", "结束",
       "好的，今天就先沟通到这里，您的意见我会如实反馈，"
       "后续如有进展会再与您联系。感谢您的配合，祝您生活愉快，再见。",
       score=90, remark="结束：补充反馈与回访承诺，符合调解中立角色"),
    _t("TPL_TRANSFER_001", "N025", "STR_TRANSFER", "REQUEST_HUMAN/高风险",
       "我这边先记录您的情况，后续可由人工工作人员再联系您。", score=98, remark="转人工"),
    _t("TPL_COOLDOWN_001", "N025", "STR_COOLDOWN", "ABUSIVE_LANGUAGE",
       "我理解您现在不方便沟通，这边先不打扰您了。", score=98, remark="降温结束"),
    # 系统补充
    _t("TPL_ASK_SELF_001", "N002", "STR_PRIVACY_IDENTITY", "开场确认",
       "请问您是{name}本人吗？", ["name"], remark="系统补充：身份主问句"),
    _t("TPL_NOTICE_ASK_001", "N007", "STR_NOTICE_EXPLAIN", "通知确认",
       "请问您之前有收到过相关的短信或通知吗？", remark="系统补充"),
    _t("TPL_WILL_001", "N009", "STR_ACCEPT", "意愿确认",
       "调解是自愿的沟通方式，请问您是否愿意通过调解来处理这个事项？", remark="系统补充",
       variants=["调解是自愿免费的，您看愿不愿意通过调解来沟通处理这件事？"]),
    _t("TPL_HESITATE_001", "N012", "STR_ACCEPT", "HESITATE",
       "没关系，调解是双方自愿、免费的沟通，主要帮您把想法如实带过去，"
       "您可以慢慢说您的顾虑或想了解的地方。",
       remark="系统补充",
       variants=["没事，调解就是想听听您这边的想法，您慢慢说，看哪些方面我能帮您。",
                 "理解，您先说说目前最担心的是哪一块，我们一起看怎么处理比较合适。"]),
    _t("TPL_AMOUNT_001", "N015", "STR_DENY_DEBT", "AMOUNT_DISPUTE",
       "您对金额的异议我会如实记录，后续可以核对账单明细。", remark="系统补充"),
    _t("TPL_PLATFORM_001", "N016", "STR_DENY_DEBT", "PLATFORM_QUESTION",
       "好的，建议您核对一下相关平台的账单或合同信息，您的疑问我也会记录。", remark="系统补充"),
    _t("TPL_PLAN_ASK_001", "N017", "STR_PLAN_CONFIRM", "方案探询",
       "您看您这边目前方便怎么处理，比如大概的时间或金额？", remark="系统补充：方案主问句",
       variants=["您这边打算怎么处理呢？时间上或金额上都可以说说。",
                 "那您看，怎样的时间或金额安排，您这边比较好接受？"]),
    _t("TPL_PLAN_CONFIRM_INST_001", "N021", "STR_PLAN_CONFIRM", "PROVIDE_PLAN",
       "我跟您确认一下，您是希望分{installment_count}期、每期{installment_amount}元处理，对吗？",
       ["installment_count", "installment_amount"], remark="系统补充：分期确认"),
    _t("TPL_PLAN_ADJUST_001", "N017", "STR_PLAN_CONFIRM", "PLAN_ADJUST",
       "好的，那您看怎样的时间或金额安排，您这边可以接受？", remark="系统补充"),
    _t("TPL_RELAY_001", "N005", "STR_NON_SELF", "KNOWS_PERSON",
       "好的，那麻烦您方便时转告一下，请其留意短信通知，感谢您。", remark="系统补充"),
    _t("TPL_CALLBACK_OK_001", "N022", "STR_CALLBACK", "PROVIDE_PLAN",
       "好的，那{callback_time}我们再与您联系，感谢您的配合，再见。", ["callback_time"], remark="系统补充"),
    _t("TPL_RETRY_001", "ANY", None, "FALLBACK",
       "好的，您说说目前的情况就行，咱们一起看看怎么处理。",
       remark="系统补充：重试前缀（邀请用户表达，强调中立第三方协商）",
       variants=["嗯，您方便聊聊您的想法吗，我们尽量按您能接受的来。",
                 "您看您这边大致是什么打算，我们一起商量。",
                 "好的，您直接说说您现在的实际情况就行。",
                 "您说说您的考虑，我会如实把您的意见带过去。",
                 "理解，您看您这边怎么处理比较方便？"]),
    _t("TPL_FALLBACK_001", "ANY", None, "FALLBACK",
       "我这边先记录您的意见，后续可由人工工作人员再与您联系。", remark="系统补充：全局兜底（方案5.8.4）"),
    _t("TPL_ASK_AMOUNT_001", "ANY", "STR_PLAN_CONFIRM", "ASK_SLOT",
       "您大概能处理多少金额呢？", remark="系统补充：追问槽位"),
    _t("TPL_ASK_DATE_001", "ANY", "STR_PLAN_CONFIRM", "ASK_SLOT",
       "您看大概什么时候方便处理？", remark="系统补充：追问槽位"),
    _t("TPL_ASK_INST_COUNT_001", "ANY", "STR_INSTALLMENT", "ASK_SLOT",
       "您希望分几期处理呢？", remark="系统补充：追问槽位"),
    _t("TPL_ASK_INST_AMOUNT_001", "ANY", "STR_INSTALLMENT", "ASK_SLOT",
       "每期大概能承担多少金额？", remark="系统补充：追问槽位"),
    _t("TPL_ASK_CALLBACK_001", "ANY", "STR_CALLBACK", "ASK_SLOT",
       "请问什么时间联系您比较方便？", remark="系统补充：追问槽位"),
    _t("TPL_AMOUNT_RECHECK_001", "ANY", "STR_PLAN_CONFIRM", "金额复核",
       "不好意思，金额这边我没有记准，麻烦您再说一遍具体金额好吗？",
       remark="系统补充：金额异常复核（防ASR误识别大额承诺）"),
]

# 槽位 → 追问话术
SLOT_QUESTIONS = {
    "repayment_amount": "TPL_ASK_AMOUNT_001",
    "repayment_date": "TPL_ASK_DATE_001",
    "installment_count": "TPL_ASK_INST_COUNT_001",
    "installment_amount": "TPL_ASK_INST_AMOUNT_001",
    "callback_time": "TPL_ASK_CALLBACK_001",
}

# 这些模板自带结束语，终态时不再追加 TPL_END_001
NO_END_APPEND = {"TPL_CALLBACK_OK_001", "TPL_RELAY_001", "TPL_COOLDOWN_001", "TPL_END_001"}

# ---------------- 08_Prompt组件库（Excel 原表） ----------------
def _c(cid, ctype, nodes, cond, content, prio, required, remark=""):
    return dict(component_id=cid, component_type=ctype, nodes=nodes, enable_condition=cond,
                content=content, priority=prio, required=required, enabled=True, remark=remark)


COMPONENTS = [
    _c("ROLE", "角色组件", "ALL", "调用LLM时",
       "你是民事调解员，作为独立第三方协助借贷双方沟通，不是催收。"
       "语气温和、共情、专业、克制；先听用户的难处与意愿，再一起寻找双方都能接受的方案。"
       "绝不施压、不威胁、不评判、不承诺减免结果。所有方案最终都需要对方确认。", 100, True),
    _c("NODE", "节点组件", "ALL", "调用LLM时",
       "当前节点：{node_name}。节点目标：{node_goal}。", 90, True, "由节点表动态填充"),
    _c("USER_TEXT", "用户输入组件", "ALL", "调用LLM时", "用户刚才说：{user_text}", 90, True),
    _c("CLASSIFY", "识别结果组件", "ALL", "调用LLM时",
       "系统识别：意图={intent}，抗性={objection}，风险={risk}。", 85, False),
    _c("STRATEGY", "策略组件", "ALL", "调用LLM时", "处理策略：{strategy_instruction}", 90, True, "由策略库填充"),
    _c("SCRIPT", "参考话术组件", "ALL", "有模板时", "参考话术：{template_text}", 80, False, "由话术库填充"),
    _c("CASE_SAFE", "案件变量组件", "N006,N017,N021", "identity_confirmed=true",
       "可用案件变量：姓名={name}，平台={platform_name}，金额={total_amount}。", 70, False, "仅确认本人后使用"),
    _c("PRIVACY", "隐私组件", "N001,N002,N003,N004,N005", "identity_confirmed=false",
       "未确认本人前，不得披露平台、金额、欠款、逾期、案号等具体信息。", 100, True, "身份阶段必选"),
    _c("COMPLIANCE", "合规组件", "ALL", "调用LLM时",
       "禁止威胁、冒充法院、泄露隐私、承诺减免结果、要求立即还款。", 100, True),
    _c("OUTPUT", "输出约束组件", "ALL", "调用LLM时",
       "只输出调解员下一句话，不超过30字，不要解释，不要编号。", 100, True),
    # ---- 系统补充：对话记忆 / 已知信息 / 防重复（解决跨轮一致性与复读机感） ----
    _c("HISTORY", "对话历史组件", "ALL", "调用LLM时",
       "最近对话：\n{history_text}", 88, False, "系统补充：跨轮一致性"),
    _c("KNOWN", "已知信息组件", "ALL", "调用LLM时",
       "已确认信息：{known_facts}。不要重复询问已知信息。", 84, False, "系统补充"),
    _c("NO_REPEAT", "防重复组件", "ALL", "调用LLM时",
       "你最近说过：{recent_bot_lines}。请换不同的措辞，不要重复同样的话。", 83, False,
       "系统补充：防复读机"),
    _c("TONE", "情绪适配组件", "ALL", "调用LLM时",
       "用户当前情绪：{emotion}。{tone_guidance}", 86, False,
       "系统补充：根据情绪挑选共情措辞"),
]

# UNKNOWN长尾自由应答（受限）：简短回应 + 拉回流程，由 orchestrator 在 fallback 前调用
FREEFORM_STRATEGY = dict(
    strategy_id="STR_FREEFORM", strategy_name="长尾自由应答",
    instruction=("用户刚才的回应没有命中标准流程。用一句话先承接用户语气（理解/确认/共情），"
                 "再用自然口语把话题引回当前节点目标；严禁逐字重复你最近说过的话，"
                 "不编造案件细节、不做法律结论、不承诺减免或放款，"
                 "若参考话术非空，可借鉴其措辞但要换一种说法。"))
# 长尾应答启用 SCRIPT/CASE_SAFE/TONE：让模型看到节点主问句与用户情绪，避免无源即兴
FREEFORM_COMPONENTS = ["ROLE", "HISTORY", "NODE", "USER_TEXT", "KNOWN", "CLASSIFY",
                       "TONE", "STRATEGY", "SCRIPT", "CASE_SAFE", "PRIVACY",
                       "COMPLIANCE", "NO_REPEAT", "OUTPUT"]

# 用户明确要求停止联系 → 进DNC谢绝名单（外呼策略层强制生效）
DNC_PHRASES = ("别再打", "不要再打", "别打了", "别给我打", "不要给我打", "再打我就")

# ---------------- 09_合规规则库（Excel 原表；intercept=文本拦截，行为类由路由/质检保障） ----------------
def _cr(rid, rtype, kws, stage, risk, req, action, repair, dyn=None, intercept=True, remark=""):
    return dict(rule_id=rid, rule_type=rtype, trigger_keywords=kws, stage=stage, risk_level=risk,
                requirement=req, action=action, repair_text=repair, dynamic_kind=dyn,
                intercept=intercept, enabled=True, remark=remark)


COMPLIANCE_RULES = [
    _cr("CR001", "隐私披露", ["欠款", "逾期", "案号", "案件编号", "借款", "贷款"], "身份核验", "严重",
        "未确认本人前不得披露敏感信息", "拦截并替换", "为保护信息安全，我需要先确认是否本人。",
        dyn="PRIVACY_PRE_IDENTITY", remark="全局最高优先级；同时动态拦截平台名/金额数字"),
    _cr("CR002", "身份冒充", ["法院", "法官", "执行局", "公安", "检察院", "已经判", "判决"], "全流程", "严重",
        "不得冒充司法或执法身份", "拦截并替换", "我这边是调解机构工作人员。"),
    _cr("CR003", "威胁恐吓",
        ["起诉你", "告你", "后果自负", "列入失信", "失信名单", "黑名单", "必须今天", "马上还",
         "立即还", "你违法", "拘留", "上门", "爆通讯录", "通讯录", "联系你家人"],
        "全流程", "严重", "不得威胁、恐吓、施压", "拦截并替换", "调解是自愿的，我会如实记录您的意见。"),
    _cr("CR004", "承诺结果",
        ["一定可以减免", "一定减免", "肯定能减", "保证通过", "肯定通过", "肯定不用还",
         "一定不会起诉", "百分百", "包过", "就能结清"],
        "方案协商", "严重", "不得承诺减免、分期或处理结果", "拦截并替换",
        "您的诉求我可以记录，具体结果需要后续核实。"),
    _cr("CR005", "第三方披露", ["欠款", "金额", "借款", "逾期", "贷款"], "身份核验", "严重",
        "不得向第三方披露案情", "拦截并替换", "为保护隐私，我不便说明具体内容。",
        dyn="THIRD_PARTY", remark="对方非本人时动态拦截平台名/金额数字"),
    _cr("CR006", "骚扰风险", [], "全流程", "高", "用户拒绝联系应记录并停止追问", "结束或转人工",
        "好的，我会记录您的意见，先不打扰您。", intercept=False, remark="行为类：由R012/R140等路由保障"),
    _cr("CR007", "诈骗敏感", [], "全流程", "高", "应认可谨慎并引导核验", "模板直出/转人工",
        "您的谨慎是对的，可以先通过官方渠道核验。", intercept=False, remark="行为类：由R002路由保障"),
    _cr("CR008", "辱骂情绪", [], "全流程", "高", "不得对抗，应降温或结束", "降温结束",
        "我理解您现在不方便沟通，这边先不打扰您了。", intercept=False, remark="行为类：由R004路由保障"),
    _cr("CR009", "法律解释边界", ["会坐牢", "要坐牢", "判刑", "会被抓", "肯定败诉", "构成犯罪"],
        "全流程", "中", "机器人不得提供确定法律结论", "转人工/中性表达",
        "具体法律问题建议由专业人员进一步说明。"),
    _cr("CR010", "验证码/转账",
        ["把验证码", "发验证码", "提供验证码", "验证码告诉", "报一下验证码",
         "转账给我", "转到我", "私人账户", "个人账户", "加我微信", "加我QQ"],
        "全流程", "严重", "不得索要验证码或个人转账", "拦截",
        "我们不会索要验证码，也不会要求向个人账户转账。"),
]

# ---------------- 10_通话质检规则（Excel 原表） ----------------
QC_RULES = [
    dict(qc_id="QC001", dimension="身份核验", checkpoint="是否确认本人后再披露案件信息",
         rule_text="未确认本人披露平台/金额为严重违规", severity="严重", deduct=30,
         manual_review=True, output_field="privacy_violation"),
    dict(qc_id="QC002", dimension="流程推进", checkpoint="是否完成关键SOP节点",
         rule_text="缺少身份确认/意愿确认/结果总结扣分", severity="中", deduct=10,
         manual_review=False, output_field="sop_complete"),
    dict(qc_id="QC003", dimension="调解意愿", checkpoint="是否明确询问调解意愿",
         rule_text="未询问直接进入方案扣分", severity="中", deduct=10,
         manual_review=False, output_field="willingness_checked"),
    dict(qc_id="QC004", dimension="抗性识别", checkpoint="是否正确识别拒调、没钱、否认欠款等",
         rule_text="低置信度多轮需人工复核", severity="中", deduct=10,
         manual_review=True, output_field="intent_accuracy"),
    dict(qc_id="QC005", dimension="方案收集", checkpoint="是否收集金额、时间、分期要素",
         rule_text="有意愿但未收集方案扣分", severity="低", deduct=8,
         manual_review=False, output_field="plan_collected"),
    dict(qc_id="QC006", dimension="合规表达", checkpoint="是否出现威胁/冒充/承诺结果",
         rule_text="命中CR002/CR003/CR004严重违规", severity="严重", deduct=30,
         manual_review=True, output_field="compliance_violation"),
    dict(qc_id="QC007", dimension="情绪处理", checkpoint="用户情绪激烈时是否降温/转人工",
         rule_text="继续施压扣分", severity="高", deduct=15,
         manual_review=True, output_field="emotion_handled"),
    dict(qc_id="QC008", dimension="转人工", checkpoint="高风险场景是否转人工或记录",
         rule_text="未转人工扣分", severity="高", deduct=15,
         manual_review=True, output_field="human_transfer_needed"),
    dict(qc_id="QC009", dimension="通话结果", checkpoint="是否有明确结果归档",
         rule_text="缺少结果字段扣分", severity="低", deduct=5,
         manual_review=False, output_field="call_result"),
    dict(qc_id="QC010", dimension="响应延迟", checkpoint="机器人响应是否过慢",
         rule_text="P95超过1.8秒需优化", severity="低", deduct=5,
         manual_review=False, output_field="latency_score"),
]

# ---------------- 02_案件字段表：中文表头 → 字段名（Excel导入用） ----------------
CASE_FIELD_CN_MAP = {
    "当事人姓名": "debtor_name", "姓名": "debtor_name",
    "性别": "debtor_gender", "手机号": "debtor_phone", "联系电话": "debtor_phone",
    "证件后四位": "id_last4", "案件编号": "case_id",
    "平台/产品名称": "platform_name", "平台名称": "platform_name", "平台": "platform_name",
    "本金": "principal_amount", "标的/合计金额": "total_amount", "合计金额": "total_amount",
    "总金额": "total_amount", "逾期天数": "overdue_days",
    "申请方/委托方": "creditor_name", "委托方": "creditor_name",
    "调解机构": "mediation_org", "官方核验渠道": "official_verify_channel",
    "通知状态": "notice_status",
}

# 演示案件（与模板示例值一致）
DEMO_CASE = dict(
    case_id="CASE20260610001", debtor_name="张三", debtor_gender="男",
    debtor_phone="138****8888", platform_name="橘子分期", principal_amount=10000,
    total_amount=16000, overdue_days=180, creditor_name="辽宁友信资产管理",
    mediation_org="XX民商事调解中心", official_verify_channel="短信链接/官方电话/平台入口",
    notice_status="已发送", case_status="待跟进",
)
